# Generated by Django 5.2 on 2025-04-10 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OJTHoursTracker_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='tbl_user',
        ),
    ]
