# Generated by Django 5.2 on 2025-04-26 02:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OJTHoursTracker_app', '0002_alter_user_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeEntry',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('morning_in', models.TimeField(blank=True, null=True)),
                ('morning_out', models.TimeField(blank=True, null=True)),
                ('afternoon_in', models.TimeField(blank=True, null=True)),
                ('afternoon_out', models.TimeField(blank=True, null=True)),
                ('evening_in', models.TimeField(blank=True, null=True)),
                ('evening_out', models.TimeField(blank=True, null=True)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(db_column='id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tbl_time_entry',
            },
        ),
    ]
