# Generated by Django 5.2 on 2025-04-26 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OJTHoursTracker_app', '0003_timeentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeentry',
            name='total_hours',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
