# Generated by Django 5.2 on 2025-04-26 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OJTHoursTracker_app', '0004_timeentry_total_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rendered_hours',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='required_hours',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
