# Generated by Django 5.2 on 2025-04-26 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OJTHoursTracker_app', '0005_user_rendered_hours_user_required_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='required_hours',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
