# Generated by Django 5.2 on 2025-05-01 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OJTHoursTracker_app', '0006_alter_user_required_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rendered_hours',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
